CREATE TABLE TPROJETO (
   CODIGO_PROJETO NUMBER(5) NOT NULL,
   TITULO VARCHAR2(100) NOT NULL,
   INSTITUICAO VARCHAR2(150),
   DURACAO VARCHAR2(5),
   CODIGO_AREA NUMBER(5),
   RG_PESQUISADOR VARCHAR(15),
   CONSTRAINT PK_TPROJETO PRIMARY KEY(CODIGO_PROJETO),
   CONSTRAINT FK_CODIGO_AREA FOREIGN KEY(CODIGO_AREA) REFERENCES TAREA,
   CONSTRAINT FK_RG_PESQUISADOR FOREIGN KEY(RG_PESQUISADOR) REFERENCES TPESQUISADOR(RG_PESQUISADOR) 
);


INSERT INTO TPROJETO(CODIGO_PROJETO,TITULO,INSTITUICAO,DURACAO)
VALUES(12345,'Projeto 01','CES/JF','3a');

INSERT INTO TPROJETO(CODIGO_PROJETO,TITULO,INSTITUICAO,DURACAO)
VALUES(6789,'Projeto 02','CES/JF','4a');

INSERT INTO TPROJETO(CODIGO_PROJETO,TITULO,INSTITUICAO,DURACAO)
VALUES(10112,'Projeto 02','CES/JF','5a');



CREATE TABLE TPESQUISADOR(
    NOME VARCHAR2(100) NOT NULL,
    GRAU_INSTITUICAO VARCHAR2(100),
    INSTITUICAO VARCHAR2(150),
    SEXO VARCHAR2(1),
    DATA_NASCIMENTO DATE,
    CPF_PESQUISADOR VARCHAR(14),
    RG_PESQUISADOR VARCHAR(15) NOT NULL,
    CONSTRAINT PK_TPESQUISADOR PRIMARY KEY(RG_PESQUISADOR)
    

);



INSERT INTO TPESQUISADOR(NOME,GRAU_INSTITUICAO, INSTITUICAO, SEXO, DATA_NASCIMENTO
, CPF_PESQUISADOR, RG_PESQUISADOR)
VALUES('Rafael','Graduando','Ces/jf','M',SYSDATE + 1,'111.111.111-11','mg-120.11.52');

INSERT INTO TPESQUISADOR(NOME,GRAU_INSTITUICAO, INSTITUICAO, SEXO, DATA_NASCIMENTO
, CPF_PESQUISADOR, RG_PESQUISADOR)
VALUES('Wagner','Graduando','Ces/jf','F',SYSDATE - 1 ,'222.111.222-24','mg-150.31.22');

INSERT INTO TPESQUISADOR(NOME,GRAU_INSTITUICAO, INSTITUICAO, SEXO, DATA_NASCIMENTO
, CPF_PESQUISADOR, RG_PESQUISADOR)
VALUES('Lucas','Graduando','Ces/jf','F',SYSDATE - 1 ,'333.128.212-92','mg-124.24.24');

CREATE TABLE TAREA(
    DESCRICAO VARCHAR2(200),
    NOME VARCHAR2(100) NOT NULL,
    INDICE VARCHAR2(100),
    CODIGO_AREA NUMBER(5,0) NOT NULL,
    CONSTRAINT PK_TAREA PRIMARY KEY (CODIGO_AREA)
);



INSERT INTO TAREA(DESCRICAO,NOME,INDICE,CODIGO_AREA)
VALUES('Estuda o dado, mediante as suas diversas manifestações','Ciência de Dados','01','5478');


CREATE TABLE TASSESSOR(
    NOME VARCHAR(100) NOT NULL,
    GRAU_INSTITUICAO VARCHAR2(100),
    INSTITUICAO VARCHAR2(150) NOT NULL,
    SEXO VARCHAR2(1) NOT NULL,
    RG_ASSESSOR VARCHAR2(15) NOT NULL,
    DATA_NASCIMENTO DATE,
    CPF_ASSESSOR VARCHAR2(14),
    CONSTRAINT PK_TASSESSOR PRIMARY KEY(RG_ASSESSOR)
    
    

);



INSERT INTO TASSESSOR(NOME, GRAU_INSTITUICAO, INSTITUICAO,SEXO,RG_ASSESSOR,
DATA_NASCIMENTO, CPF_ASSESSOR)
VALUES('Joaquim','5','Cesjf','M','MG-15.780.710',SYSDATE,'128.115.079-24');




CREATE TABLE TAPTO(
    CODIGO_AREA NUMBER(5) NOT NULL,
    RG_ASSESSOR VARCHAR2(15) NOT NULL,
    CONSTRAINT FK_TAREA FOREIGN KEY(CODIGO_AREA) REFERENCES TAREA(CODIGO_AREA),
    CONSTRAINT FK_TASSESSOR FOREIGN KEY(RG_ASSESSOR) REFERENCES TASSESSOR(RG_ASSESSOR)

);


CREATE TABLE TRECEBE(
    CODIGO_PROJETO NUMBER(5),
    RG_ASSESSOR VARCHAR2(15),
    IDENTIFICACAO NUMBER(5),
    CONSTRAINT PK_TRECEBE PRIMARY KEY(IDENTIFICACAO),
    CONSTRAINT FK_TPROJETO FOREIGN KEY(CODIGO_PROJETO) REFERENCES TPROJETO(CODIGO_PROJETO),
    CONSTRAINT FK_TASSESSOR FOREIGN KEY(RG_ASSESSOR) REFERENCES TASSESSOR(RG_ASSESSOR)
);

CREATE TABLE AGENCIA (
    RECEBE_IDENTIFICACAO NUMBER(5),
    CONSTRAINT FK_RECEBE FOREIGN KEY(RECEBE_IDENTIFICAO) REFERENCES  TRECEBE(IDENTIFICACAO)
);


CREATE TABLE FINANCIAMENTO(
    RG_ASSESSOR VARCHAR2(15),
    CONSTRAINT FK_RECEBE FOREIGN KEY(RG_ASSESSOR) REFERENCES TASSESSOR(RG_ASSESSOR)
    
);

SELECT * FROM TPESQUISADOR;
SELECT * FROM TPROJETO;
SELECT * FROM TAREA;
SELECT * FROM TASSESSOR;


DROP TABLE TPROJETO;
DROP TABLE TPESQUISADOR;
DROP TABLE TAREA;
DROP TABLE TASSESSOR;
